'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8662
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1631319494319() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1631319494319", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _195703_light_brown_wavy_geometric_gradient_background_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("195703-light-brown-wavy-geometric-gradient-background-image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Feedback_Screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Feedback Screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Feedback_Screen1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Feedback Screen1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Feedback_Screen2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Feedback Screen2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property im4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("im4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property it_services_solutions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("it-services-solutions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property solutions_GKMR30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("solutions-GKMR30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_photo_hand_holding_a_wooden_puzzle_with_the_word_solution_there_is_a_matching_puzzle_next_to_it_with_the_1098145733() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-photo-hand-holding-a-wooden-puzzle-with-the-word-solution-there-is-a-matchi"& _ 
                        "ng-puzzle-next-to-it-with-the-1098145733", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
